# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-18 22:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('potholes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('un', 'unotified'), ('ud', 'unresolved'), ('rd', 'resolved')], default='ud', max_length=2)),
                ('comment', models.TextField(max_length=4000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.DateTimeField(blank=True, null=True)),
                ('pothole', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='potholes.Pothole')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
