# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-19 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potholes', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pothole',
            name='rating',
        ),
        migrations.AlterField(
            model_name='pothole',
            name='photo',
            field=models.ImageField(default='chain_rule.PNG', upload_to='potholes/'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('pothole', 'user')]),
        ),
    ]
